#!/bin/sh

# Copyright (c) 2013 Developed by reg <entry.reg@gmail.com>
# 
# Distributed under the MIT license
# (see accompanying file LICENSE or a copy at http://opensource.org/licenses/MIT)


# see also batch variants with a standard command interpreter Windows - < cshelp.bat >
# generate help/cshelp.h 

# range of 11000 - 11999
# replacement help/gen_cshelp.py
# detail on https://bitbucket.org/3F/featuresdc/issue/1/help-cshelph-dcpp-version-revnoinc

##### variables #####

range_begin=11000
workdir=../../../help
foutput=cshelp.h
newline="\n"

### processing #

# yep., simple... in compare with cshelp.bat =_=

cd $workdir

    # init
    output=""
    dnum=$range_begin

    output+="// generated by cshelp.sh$newline"
    output+="#ifndef DCPLUSPLUS_HELP_CSHELP_H$newline"
    output+="#define DCPLUSPLUS_HELP_CSHELP_H$newline"

        for const in $( grep -hoisE "cshelp\s*=\s*([^ ]+)" *.html | sed -r "s#cshelp\s*=\s*['\"]([^'\"]+).*#\1#i")
        do
            output+="\t#define $const $dnum$newline"
            ((dnum++))
        done

    output+="#endif"

### finalize #

echo -e $output > $foutput
echo $((dnum-range_begin)) done.